### ISSUE TITLE
Have to restart node-red for zwave outputs to work

### ISSUE THREAD

**Issue by jschuryk** [OpenZWave/node-red-contrib-openzwave#10]
I think this is similar to the other issue requesting a driver restart - it seemed to be closed due to lack of feedback.

I am have a similar issue.  If I change a flow and deploy those changes, my zWave outputs do not reconnect.  It requires a restart of node-red to correct.

Running on a Raspberry Pi 2 with Aeon labs z-stick.

Thanks for any advice,

Jerry

**Comment by ekarak** [comment]
which version of node-red are you on? For me (0.9.0) it works as expected, see [relevant check in the code](https://github.com/OpenZWave/node-red-contrib-openzwave/blob/master/10-zwave.js#L258)

**Comment by AntoineLT** [comment]
You work on a more than 1 year old version of Node-RED and you do not have a problem ! Upgrade to 0.11.1 and test your node with it.

**Comment by jschuryk** [comment]
I am indeed on v0.11.1

**Comment by AntoineLT** [comment]
I speak to @ekarak not you

**Comment by ekarak** [comment]
Thank you for your feedback Antoine, 
I'll try with the latest node-red but I'm afraid I can't test it without an actual device, My "production system" is my home, and when something works, I don't touch it, I leave it working. 
Et vraiment, à quoi t'attendais-tu? c'est ne pas une service payee...
Cordiallement,
Elias

**Comment by AntoineLT** [comment]
I expected that you had a development platform to test your work on the last releases. It's ok I understand, I don't want to be unpolite with you. Thank you for your explanation of what is the purpose for you to work on Node-RED 0.9.0.
