### ISSUE TITLE
Advice needed

### ISSUE THREAD

**Issue by pastukhov** [OpenZWave/node-red-contrib-openzwave#14]
I'm trying to make zwave control panel for my home automation system.I'm using https://www.npmjs.com/package/node-red-contrib-ui for the controls.
The problem is that when i'm  sending setLevel  to a dimmer i'm getting a bunch of value changed evets.
Some, where currState === oldState and i can easy filter out. And some where currState is incrementing or decrementing. As a result i'm getting my sliders are jumping and showing a wrong value.

To be clear
Some, where currState === oldState and i can easy filter out it. And some where currState is incrementing or decrementing. As a result i'm getting my sliders are jumping and showing a wrong value.

To be clear
'zwave in'->function, that listen for value changed event. It  check that the value is realy changed and set the topic to 'zwave/events/value/changed/nodeid/commandclass/instance/index' ->mqtt.

Then mqtt, that listen for a topic 'zwave/events/value/changed/dimmer nodeid/#' -> function, that extract currState and put it to payload -> ui slider -> function, that construct setValue JSON -> zwave out. 
 
Can you advice how to control my dimmers smooth?

**Comment by ekarak** [comment]
You have to pay attention to valueid details. You need to filter on command class, instance and index.

Στις 14 Νοεμβρίου 2015 9:45:35 μ.μ. EET, ο/η Artem Pastukhov <notifications@github.com> έγραψε:
>I'm trying to make zwave control panel for my home automation
>system.I'm using https://www.npmjs.com/package/node-red-contrib-ui for
>the controls.
>The problem is that when i'm  sending setLevel  to a dimmer i'm getting
>a bunch of value changed evets.
>Some, where currState === oldState and i can easy filter out. And some
>where currState is incrementing or decrementing. As a result i'm
>getting my sliders are jumping and showing a wrong value.
>
>To be clear
>Some, where currState === oldState and i can easy filter out it. And
>some where currState is incrementing or decrementing. As a result i'm
>getting my sliders are jumping and showing a wrong value.
>
>To be clear
>'zwave in'->function, that listen for value changed event. It  check
>that the value is realy changed and set the topic to
>'zwave/events/value/changed/nodeid/commandclass/instance/index' ->mqtt.
>
>Then mqtt, that listen for a topic 'zwave/events/value/changed/dimmer
>nodeid/#' -> function, that extract currState and put it to payload ->
>ui slider -> function, that construct setValue JSON -> zwave out. 
> 
>Can you advice how to control my dimmers smooth?
> 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenZWave/node-red-contrib-openzwave/issues/14

-- 
Sent from my mobile device with K-9 Mail. Please excuse my brevity.

**Comment by pastukhov** [comment]
Yes, i'm filtiering with:
```javascript
if (msg.topic === 'zwave: value changed'){
    msg.topic = 'zwave/events/value/changed/' +  msg.payload.value.value_id.replace(/-/g,'/');
    return msg;
}
```
and after that i'm able to subscribe to zwave/events/value/changed/9/38/1/0, that node9/commandclass38/instance1/index0/

But when i'm sending the message with topic setLevel and payload { "nodeid": 9, "cmdclass": 38, "value": "99" }, i'm seeing : 
```JSON
{  
   "nodeid":9,
   "cmdclass":38,
   "instance":1,
   "cmdidx":0,
   "oldState":0,
   "currState":3,
   "label":"Level",
   "units":"",
   "value":{  
      "value_id":"9-38-1-0",
      "node_id":9,
      "class_id":38,
      "type":"byte",
      "genre":"user",
      "instance":1,
      "index":0,
      "label":"Level",
      "units":"",
      "help":"",
      "read_only":false,
      "write_only":false,
      "is_polled":false,
      "min":0,
      "max":255,
      "value":3
   },
   "uuid":"020909c2d5c8-0xf96036b6-9"
}
```
and next

```JSON
{  
   "nodeid":9,
   "cmdclass":38,
   "instance":1,
   "cmdidx":0,
   "oldState":3,
   "currState":3,
   "label":"Level",
   "units":"",
   "value":{  
      "value_id":"9-38-1-0",
      "node_id":9,
      "class_id":38,
      "type":"byte",
      "genre":"user",
      "instance":1,
      "index":0,
      "label":"Level",
      "units":"",
      "help":"",
      "read_only":false,
      "write_only":false,
      "is_polled":false,
      "min":0,
      "max":255,
      "value":3
   },
   "uuid":"020909c2d5c8-0xf96036b6-9"
}
```
And i see that my lamp after that is at 99 level.

**Comment by pastukhov** [comment]
Are you gettig 'value changed' event with value you send?

**Comment by ekarak** [comment]
Not all ZWave devices report back their state to the controller. The best option is to have OpenZWave automatically add an association group (unique parameter for each device) for its status change. For your device, this should be the 3rd association group (taken from /etc/openzwave/zwave.me/ZME_06433.xml):
```
        <!-- Association Groups -->
        <CommandClass id="133">
                <Associations num_groups="3">
                        <Group index="1" max_associations="8" label="Group 1" auto="false"/>
                        <Group index="2" max_associations="8" label="Group 2" auto="false" />
                        <Group index="3" max_associations="8" label="Send updates" auto="true"/>
                </Associations>
        </CommandClass>
```
Use the `getAssociations` command to see if your ZWave controller (usually node nr.1) is subscribed to the 3rd association group. If yes, and you still not getting status feedback, then your device has a firmware bug :(
