### ISSUE TITLE
Open Zwave API problem

### ISSUE THREAD

**Issue by fraser73** [OpenZWave/node-red-contrib-openzwave#17]
I'm trying to get some things going with the new experimental Open Zwave API support - eventually change setpoint on my thermostat, but first just poll a switch to demonstrate it works. So I've got two input nodes both hooked up to a zwave node and a debug node.

When trigger an input, topic "enablePoll" payload "[5,37]" (node 5 is a binary switching socket), it appears in the debug, but nothing appears to happen. I've also tried an "isPolled" node for the same node, again it appears in the debug and nothing else appears to happens.

I don't know if this is a problem with me or the node-red-contrib-openzwave - do you have any suggestions?

I am using open zwave 1.4.1 and the latest versions (as of mid last week) of node-red-contrib-open-zwave and node-openzwave-shared, on a raspberry pi running wheezy with an aeon labs zstick 2.

**Comment by fraser73** [comment]
I've been having a further hack about with this, I have a thermostat which acts as a controller, linked to a boiler switch. I've setup polling on the switch using Open Zwave Control Panel and copying over the config file to the Node-Red directory. I now see the switch node spamming Node Red with status updates every 10secs (hurrah!). However I didn't see anything coming out of the Thermostat itself. As a long shot, I tried a manually triggered function, which is linked to a zwave emitter node:

```
var returnmsg={"topic": "requestNodeState", "payload": [0x0184cd15, 8]};
return returnmsg;
```
0x0184cd15 being the homeID, 8 the thermostat's node ID. This kicks the thermostat into life and it starts reporting state changes, for the duration of the session.

**Comment by ekarak** [comment]
Nice, thanks for the report! in which case I need to update the docs..

**Comment by fraser73** [comment]
I've been doing a bit more work trying to get this thing going and you may want to ignore my last statement, I think something is happening that I don't fully understand with the network. I'll update as and when I've worked out what's going on.

**Comment by fraser73** [comment]
I've done a bit more attempting to solve the problem, definitely ignore what I said above in the second comment, I'd got completely the wrong end of the stick - can we open this ticket again please?

I don't seem to be getting any response from opernzwave-shared when I trigger flows which issue API commands. For example, if I make a script using openzwave-shared to issue the following command:

`zwave.setValue(5,38,1,0,50)`

It will turn on my dimmer, to 50%. In node-red, I have a trigger and a function, if the function is:

```
var returnmsg={"topic": "setValue", "payload": [5,38,1,0,50]};
return returnmsg;
```
When triggered, I get a response of "TypeError: setValue: OpenZWave valueId not found" in the debug column. If I do anything other than setValue, I get nothing back in debug at all.

Interestingly, I've noticed this issue: https://github.com/jperkin/node-openzwave/issues/44
If, I write a script and issue a `zwave.setValue('8','67','1','25')` or `zwave.setValue(8,67,1,25)`, I get the same typeError back. (Node 8 is my thermostat).

I think I'm going to need to turn on some more detailed logging to find out what's happening, but don't really know what to switch on or how.

**Comment by fraser73** [comment]
I switched on console logging by changing the "var debug=" line to true in 10-zwave.js

If I send a `{"topic": "isPolled", "payload": [9]}` the debug output is:
`ZWaveOut#input: {"topic":"isPolled","payload":[9],"_msgid":"ad2c23a0.52d3e"}` nothing else happens, until the next node-red events.

If I send a `{"topic": "setValue", "payload": [5,38,1,0,5]}` the output is:
```
ZWaveOut#input: {"topic":"setValue","payload":[5,38,1,0,5],"_msgid":"eec622fc.1139e"}
ZWaveOut.setValue payload: [5,38,1,0,5]
2 Mar 08:41:54 - [error] [zwave-out:970d4d3e.d55d1] TypeError: setValue: OpenZWave valueId not found
```

If I send a `{"topic": "setValue", "payload": ['5','38','1','0','5']}` the output is:
```
ZWaveOut#input: {"topic":"setValue","payload":["5","38","1","0","5"],"_msgid":"a82c3b0d.57d3c8"}
ZWaveOut.setValue payload: ["5","38","1","0","5"]
2 Mar 08:44:32 - [error] [zwave-out:970d4d3e.d55d1] TypeError: setValue: OpenZWave valueId not found
```

If I send a `{"topic": "setValue", "payload": ['8','67','1','19']}` the output is:
```
ZWaveOut#input: {"topic":"setValue","payload":["8","67","1","19"],"_msgid":"322e9a19.cdd166"}
ZWaveOut.setValue payload: ["8","67","1","19"]
2 Mar 08:47:20 - [error] [zwave-out:970d4d3e.d55d1] TypeError: setValue: OpenZWave valueId not found
```
My guess is that the errors mean that the messages are being passed to node-openzwave, but I  can't work out how to switch on the node-openzwave logging, as it doesn't seem to respect the changes made to my options.xml file... I'll work on that...

**Comment by fraser73** [comment]
It has just occurred to me that the setValue would be being picked up by the existing setValue code. (duh) which may be why there is a problem there. I'm going to continue to look into why isPolled doesn't seem to be working.

**Comment by shanemadden** [comment]
@fraser73 If you can, test with the modification in https://github.com/OpenZWave/node-red-contrib-openzwave/pull/20 - your issue with getting the enablePoll call to fire may be the same one I ran into.

**Comment by ekarak** [comment]
Needless to say, i'm open to suggestions (or even better, pull requests, hehe)

**Comment by fraser73** [comment]
@shanemadden - Sorry, I am really only learning Javascript - but I can't get your solution to work. I've made a function like this:

```
var isPolledResult=global.openzwaveNodes.5.classes.38.1.0.is_polled;
var returnmsg={"topic": "isPolled", "payload": isPolledResult};
return returnmsg;
```
However it just gives a syntax error, "unknown number" on the line with "global.openzwaveNodes.5.classes.38.1.0.is_polled"

Can you help?

**Comment by shanemadden** [comment]
@fraser73 Try:

```
var openzwaveNodes = global.get("openzwaveNodes");
var isPolledResult = openzwaveNodes[5].classes[38][1][0].is_polled;
var returnmsg={"topic": "isPolled", "payload": isPolledResult};
return returnmsg;
```

**Comment by fraser73** [comment]
@shanemadden - Thanks - as soon as I saw the [], I knew what I'd done wrong! That works fine.

**Comment by shanemadden** [comment]
@fraser73 Great! I'll be looking at getting the function call working through a proper node soon.

By the way, is https://thefrinkiac7.wordpress.com/ you? (noticed the similar name on the owner's discourse user and your github account) If so, then thanks a ton - those posts got me started on using this toolchain for my z-wave network.

**Comment by fraser73** [comment]
@shanemadden Hi, yes that's me. I'm glad it can be of use and that people have actually managed to find it!

@ekarak - I think that this ticket can be closed off, if the code changes detailed above have been incorporated? It seems to work ok now, for me at least!

**Comment by ekarak** [comment]
resolving
