### ISSUE TITLE
Can't install openzwave on windows

### ISSUE THREAD

**Issue by firefox7518** [OpenZWave/node-red-contrib-openzwave#23]
Hi there

I tried to find this information but is it possible to use openzwave on windows with Node-Red? 

When I try to install I get the following:

C:\Windows\system32>npm install openzwave

> openzwave@0.0.33 install C:\Windows\system32\node_modules\openzwave
> node-gyp rebuild

C:\Windows\system32\node_modules\openzwave>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp: binding.gyp not found (cwd: C:\Windows\system32\node_modules\openzwave) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\system32\node_modules\openzwave
gyp ERR! node -v v5.10.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "openzwave"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! openzwave@0.0.33 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave@0.0.33 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openzwave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openzwave
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openzwave
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

Node Version 5.10.0 is installed and also python 2.7.

Is there anything else needed?

**Comment by ekarak** [comment]
you're trying to install 'openzwave' whereas the required library is
'openzwave-shared'.
Please try:

C:\Windows\system32>npm install openzwave-shared

Thanks

2016-04-04 17:14 GMT+03:00 Andreas Messerli <notifications@github.com>:

> Hi there
>
> I tried to find this information but is it possible to use openzwave on
> windows with Node-Red?
>
> When I try to install I get the following:
>
> C:\Windows\system32>npm install openzwave
>
> openzwave@0.0.33 install C:\Windows\system32\node_modules\openzwave
> node-gyp rebuild
>
> C:\Windows\system32\node_modules\openzwave>if not defined
> npm_config_node_gyp (node "C:\Program
> Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js"
> rebuild ) else (node "" rebuild )
> gyp: binding.gyp not found (cwd:
> C:\Windows\system32\node_modules\openzwave) while trying to load binding.gyp
> gyp ERR! configure error
> gyp ERR! stack Error: gyp failed with exit code: 1
> gyp ERR! stack at ChildProcess.onCpExit (C:\Program
> Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
> gyp ERR! stack at emitTwo (events.js[image: :100:]13)
> gyp ERR! stack at ChildProcess.emit (events.js:185:7)
> gyp ERR! stack at Process.ChildProcess._handle.onexit
> (internal/child_process.js:204:12)
> gyp ERR! System Windows_NT 10.0.10586
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program
> Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js"
> "rebuild"
> gyp ERR! cwd C:\Windows\system32\node_modules\openzwave
> gyp ERR! node -v v5.10.0
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> npm WARN enoent ENOENT: no such file or directory, open
> 'C:\Windows\system32\package.json'
> npm WARN system32 No description
> npm WARN system32 No repository field.
> npm WARN system32 No README data
> npm WARN system32 No license field.
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program
> Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "openzwave"
> npm ERR! node v5.10.0
> npm ERR! npm v3.8.3
> npm ERR! code ELIFECYCLE
>
> npm ERR! openzwave@0.0.33 install: node-gyp rebuild
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the openzwave@0.0.33 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm
> installed.
> npm ERR! If you do, this is most likely a problem with the openzwave
> package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR! node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project
> with:
> npm ERR! npm bugs openzwave
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! npm owner ls openzwave
> npm ERR! There is likely additional logging output above.
>
> npm ERR! Please include the following file with any support request:
> npm ERR! C:\Windows\system32\npm-debug.log
>
> Node Version 5.10.0 is installed and also python 2.7.
>
> Is there anything else needed?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenZWave/node-red-contrib-openzwave/issues/23>
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by firefox7518** [comment]
Hi forgot to mention that. I already tried that too:

C:\Users\Andi\AppData\Roaming\npm\node_modules\node-red\node_modules>npm install openzwave-shared

> openzwave-shared@1.1.9 preinstall C:\Users\Andi\AppData\Roaming\npm\node_modules\node-red\node_modules\.staging\openzwave-shared-e5fef16a
> node lib/install-ozw.js

Installing Open Z-Wave
Installing dependencies to C:\Users\Andi\AppData\Local\Temp\ozwinstall-inee7co9a4i
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Andi\AppData\Local\Temp\ozwinstall-inee7co9a4i\package.json'
npm WARN ozwinstall-inee7co9a4i No description
npm WARN ozwinstall-inee7co9a4i No repository field.
npm WARN ozwinstall-inee7co9a4i No README data
npm WARN ozwinstall-inee7co9a4i No license field.
Temp Path: C:\Users\Andi\AppData\Local\Temp\ozwinstall-inee7co9a4i
Install Path: C:\Users\Andi\AppData\Local\OpenZWave
Downloading open zwave source.
Extracting open zwave source.
Building open zwave
static library binding.gyp:openzwave#target has several files with the same basename:
  EventImpl: cpp/src/platform/windows/EventImpl.cpp cpp/src/platform/winRT/EventImpl.cpp
  SerialControllerImpl: cpp/src/platform/windows/SerialControllerImpl.cpp cpp/src/platform/winRT/SerialControllerImpl.cpp
  ThreadImpl: cpp/src/platform/windows/ThreadImpl.cpp cpp/src/platform/winRT/ThreadImpl.cpp
  TimeStampImpl: cpp/src/platform/windows/TimeStampImpl.cpp cpp/src/platform/winRT/TimeStampImpl.cpp
  MutexImpl: cpp/src/platform/windows/MutexImpl.cpp cpp/src/platform/winRT/MutexImpl.cpp
  WaitImpl: cpp/src/platform/windows/WaitImpl.cpp cpp/src/platform/winRT/WaitImpl.cpp
  LogImpl: cpp/src/platform/windows/LogImpl.cpp cpp/src/platform/winRT/LogImpl.cpp
  FileOpsImpl: cpp/src/platform/windows/FileOpsImpl.cpp cpp/src/platform/winRT/FileOpsImpl.cpp
libtool on Mac cannot handle that. Use --no-duplicate-basename-check to disable this validation.
gyp: Duplicate basenames in sources section, see list above
C:\Users\Andi\AppData\Roaming\npm\node_modules\node-red\node_modules\.staging\openzwave-shared-e5fef16a\lib\install-ozw.js:144
  throw err;
  ^

Error: `gyp` failed with exit code: 1
    at ChildProcess.onCpExit (C:\Users\Andi\AppData\Local\Temp\ozwinstall-inee7co9a4i\node_modules\node-gyp\lib\configure.js:305:16)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
node-red@0.13.3 C:\Users\Andi\AppData\Roaming\npm\node_modules\node-red
`-- ws@0.8.1
  +-- bufferutil@1.2.1
  | +-- bindings@1.2.1
  | `-- nan@2.2.1
  `-- utf-8-validate@1.2.1

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "openzwave-shared"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! openzwave-shared@1.1.9 preinstall: `node lib/install-ozw.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.1.9 preinstall script 'node lib/install-ozw.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install-ozw.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openzwave-shared
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andi\AppData\Roaming\npm\node_modules\node-red\node_modules\npm-debug.log

Just saw that it is using largely different dirs during this process. I never changed anything on the node installation and node-red installation so my folder structure on Win10 is: C:\Users\Andi\AppData\Roaming\npm\node_modules\node-red\node_modules\

**Comment by ekarak** [comment]
First of all, this is *unrelated* to the node-red node, therefore I'm closing this issue.  This is an issue with `openzwave-shared`. 
Please try to clean up your temporary directories and try to install. If it fails again, please [raise the issue in the openzwave-shred project](https://github.com/OpenZWave/node-openzwave-shared/issues)
