### ISSUE TITLE
New 'radio' palette category?

### ISSUE THREAD

**Issue by maxwellhadley** [OpenZWave/node-red-contrib-openzwave#24]
Hi,

I'm the maintainer of the node-red-contrib-fxcom package, using the 'other' universal 433MHz transceiver device. The number of nodes in my package is growing, and I'm thinking about moving them all to my own palette category, rather than cluttering up input & output. But on reflection, it seems more appropriate to create a new 'Radio' category, in which I think the Tellstick and Z-Wave nodes would also fit. How would you feel about such a re-categorization?

Max Hadley

**Comment by ekarak** [comment]
You might be right. Could an even more abstract category like "Automation" or "Home Automation" be more fitting though?

**Comment by maxwellhadley** [comment]
I like this idea! It's a pity that 'domotica' hasn't made it across into English though. Since you can't have a space (or a '-') in a palette category, how does 'home_automation' sound?

**Comment by ekarak** [comment]
We could also tag these nodes under the even more generic term "BMS" (building management system), that could also include the [KNX](http://www.knx.org) [Node Red node](https://github.com/ekarak/node-red-contrib-eibd/) I'm also developing. KNX is a wired RS-485-like protocol that's wildly popular in Europe, but requires cabling between the nodes. The discussion on node grouping could go on forever I guess :)

**Comment by maxwellhadley** [comment]
Yeah I spotted the KNX node. I think it would squeeze in under 'home automation' OK. BMS is a bit of a specialist term, like 'domotica'. I've published the latest version of my rfxcom nodes under 'home automation' (which is shown as 'home_automation' in the editor). Join in if you want!

**Comment by ekarak** [comment]
ok, this is now done. Resolving
