### ISSUE TITLE
Polling problem (too fast!)

### ISSUE THREAD

**Issue by fraser73** [OpenZWave/node-red-contrib-openzwave#27]
Hi... I've got a problem with a node that I'm polling - It's a permanently powered node, which I'm polling switch_binary (37). I have setup the polling using open-zwave-control-panel and copied the zwcfg file to .../node-red-contrib-openzwave/node_modules/openzwave-shared/ 
The switch in question used to report once every 30secs or so, now it's reporting every second. When I run ozwcp, the polling works fine at about once every 30secs.

I'm not really sure what further information you need, so let me know, anything I can do.

It's running on a Pi2, Raspbian Jessie, fully up to date. Node v0.12.15, Node Red v0.14.3, node-red-contrib-openzwave 1.1.7, openzwave-shared 1.2.0.

I don't know if the problem is with node-red-contrib-openzwave or openzwave-shared, so I'm taking a guess and posting here first.

**Comment by ekarak** [comment]
You probably need to call SetPollInterval to set a less intensive polling.
I assume 1 sec is the default interval and OZWCP is overwriting this to 30
sec.
http://www.openzwave.com/dev/classOpenZWave_1_1Manager.html#ac7032ff3978d645b6dcd3284a8055207



2016-07-07 17:53 GMT+03:00 fraser73 <notifications@github.com>:

> Hi... I've got a problem with a node that I'm polling - It's a permanently
> powered node, which I'm polling switch_binary (37). I have setup the
> polling using open-zwave-control-panel and copied the zwcfg file to
> .../node-red-contrib-openzwave/node_modules/openzwave-shared/
> The switch in question used to report once every 30secs or so, now it's
> reporting every second. When I run ozwcp, the polling works fine at about
> once every 30secs.
>
> I'm not really sure what further information you need, so let me know,
> anything I can do.
>
> It's running on a Pi2, Raspbian Jessie, fully up to date. Node v0.12.15,
> Node Red v0.14.3, node-red-contrib-openzwave 1.1.7, openzwave-shared 1.2.0.
>
> I don't know if the problem is with node-red-contrib-openzwave or
> openzwave-shared, so I'm taking a guess and posting here first.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenZWave/node-red-contrib-openzwave/issues/27>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAj4KYrzhyMn4KmgdUektYgg35isig4zks5qTRLngaJpZM4JHKfh>
> .
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by fraser73** [comment]
That appears to be the case... I changed what turned out to be 500ms poll interval in the config node to 10000ms and I get a much sedate poll rate. The odd thing is that I've never seen this as an issue before and the poll interval has always been "500" on my system, which is why I didn't try this as a solution in the first place...

I also noted that it appears that I need to restart node-red for the poll interval to take effect, is this correct? I presume it's a driver initialisation thing?

**Comment by fraser73** [comment]
Anyway, thanks for your help here...

**Comment by ekarak** [comment]
resolving
