### ISSUE TITLE
use with minimote

### ISSUE THREAD

**Issue by travisghansen** [OpenZWave/node-red-contrib-openzwave#28]
I'm pretty new to zwave so forgive me ignorance.

I've got the minimote setup in secondary controller scene mode.  For some reason I'm note seeing the status/events firing off anything in node red.

When using ozwcp I can see the output correctly so I know it's working correctly on that front.

Is it possible to make node-red catch the scene events?

**Comment by travisghansen** [comment]
After enabling debug I'm seeing this:

```
Dec 17 15:40:54 hub-wireless.lan Node-RED[26327]: 2016-12-17 15:40:54.453 Detail,
Dec 17 15:40:54 hub-wireless.lan Node-RED[26327]: 2016-12-17 15:40:54.454 Info, Node005, ApplicationCommandHandler - Unhandled Command Class 0x2b
```

**Comment by ekarak** [comment]
> Unhandled Command Class 0x2b
That is *weird*, because 0x2b is the SceneActivation class:
```
$ grep -i "0x2b" *
SceneActivation.h:	/** \brief Implements COMMAND_CLASS_SCENEACTIVATION (0x2B), a Z-Wave device command class.
SceneActivation.h:		static uint8 const StaticGetCommandClassId(){ return 0x2B; }	
```

my best guess at this point is you have a really ancient OpenZWave version on your system.

**Comment by travisghansen** [comment]
@ekarak I was running git master
