### ISSUE TITLE
Testing OpenZWave API

### ISSUE THREAD

**Issue by cflurin** [OpenZWave/node-red-contrib-openzwave#31]
Hi,

I'm testing the new OpenZWave API.

these work: 
```
{"topic": "getNodeStatistics", "payload": {"args": [11]}}
and
{"topic": "getLibraryVersion", "payload":{"args": [1]}}
```
but this:
```
{"topic": "requestConfigParam", "payload": {"prependHomeId": true, "args": [3,3]}}
```
returns `OpenZwave: direct API call success, result=undefined`

node 3 = Roller Shutter Controller 2 FGRM-222
param 3 = Reports type

**Comment by ekarak** [comment]
Yes, that's the expected behaviour. Most calls in OpenZWave are asynchronous, meaning they do not return back a value immediately, but only through a callback. You should see "controller command" notifications in the "zwave-in" node shortly after the USB controller has received the requested info from the zwave node. Therefore, if your node is for example a battery operated device, it will only wake up at predetermined intervals and the response might come minutes, even hours later.

**Comment by cflurin** [comment]
I don't see any msg from the zwave-in node, it's wired to a debug node. Node 3 is a device without battery.
Could you please confirm that it works on your system.

**Comment by ekarak** [comment]
Please refer to the main OpenZWave documentation:

http://www.openzwave.com/dev/classOpenZWave_1_1Manager.html#aa35d05ad94fc7dcfb797de127e114080

> Request the value of a configurable parameter from a device. Some devices have various parameters that can be configured to control the device behavior. These are not reported by the device over the Z-Wave network, but can usually be found in the device's user manual. This method requests the value of a parameter from the device, and then returns immediately, without waiting for a response. If the parameter index is valid for this device, and the device is awake, the value will eventually be reported via a ValueChanged notification callback. The ValueID reported in the callback will have an index set the same as _param and a command class set to the same value as returned by a call to Configuration::StaticGetCommandClassId.

... the command class for configuration ValueID's is  0x70 (112 decimal). Therefore please do:
- run `node`
- load up the test2 script with .load : `.load test2.js`
- once you see the "scan complete" message, type `nodes` and examine each node's contents for valueID's beloging to that class:
Therefore, to get node 3's configuration values, use:
`nodes[3].classes[112]`

**Please note, this is an API question on the underlying C++ library, not the Node.JS adapter.**

**Comment by cflurin** [comment]
Ok, I'll try tomorrow. As far as I remember this did work with version 1.1.7.
I also used ozwcp and all my devices are saved in the zwcfg_homeid.xml file, so I know the cc's and params.
