### ISSUE TITLE
OpenZWave Thermostat (Danfoss/Devolo)

### ISSUE THREAD

**Issue by profpohl** [OpenZWave/node-red-contrib-openzwave#32]
I am trying to set the setPoint of my Devolo-Thermostat and have no idea how to manage this. I think it is related to #17 but I couldn't find the answer for me there.

I included my Thermostat and get following results:
30 Jan 16:29:18 - [info] OpenZwave: only/|R|W| (nodeid-cmdclass-instance-index): type : current state
30 Jan 16:29:18 - [info] OpenZwave:     |*| | 17-49-1-1: Temperature:   21.27
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-67-1-2: Cooling 1:     0.0
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-70-1-1: Monday:        undefined
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-70-1-2: Tuesday:       undefined
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-70-1-3: Wednesday:     undefined
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-70-1-4: Thursday:      undefined
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-70-1-5: Friday:        undefined
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-70-1-6: Saturday:      undefined
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-70-1-7: Sunday:        undefined
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-70-1-8: Override State:        None
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-70-1-9: Override Setback:      127
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-117-1-0: Protection:   Unprotected
30 Jan 16:29:18 - [info] OpenZwave:     |*| | 17-128-1-0: Battery Level:        90
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-129-1-0: Day:  Tuesday
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-129-1-1: Hour: 7
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-129-1-2: Minute:       9
30 Jan 16:29:18 - [info] OpenZwave:     | | | 17-132-1-0: Wake-up Interval:     240
30 Jan 16:29:18 - [info] OpenZwave:     |*| | 17-132-1-1: Minimum Wake-up Interval:     60
30 Jan 16:29:18 - [info] OpenZwave:     |*| | 17-132-1-2: Maximum Wake-up Interval:     1800
30 Jan 16:29:18 - [info] OpenZwave:     |*| | 17-132-1-3: Default Wake-up Interval:     300
30 Jan 16:29:18 - [info] OpenZwave:     |*| | 17-132-1-4: Wake-up Interval Step:        60
30 Jan 16:29:18 - [info] OpenZwave:     |*| | 17-134-1-0: Library Version:      6
30 Jan 16:29:18 - [info] OpenZwave:     |*| | 17-134-1-1: Protocol Version:     3.67
30 Jan 16:29:18 - [info] OpenZwave:     |*| | 17-134-1-2: Application Version:  1.00

Then I tried to set a value through the Open Zwave API and tried several variations of:
nodeId: 17, cmdclass: 67, instance: 1, cmdidx: 2, value: 23.5
(e.g. msg.payload = [17,67,1,2,23.5]; msg.topic = "setValue", ...)
but always get this respond "TypeError: setValue: OpenZWave valueId not found"

What is the mistake with my thinking? 
I am using open zwave 1.4.1, node-red-contrib-openzwave 1.2.0 and node-red 0.15.3 on a raspberry 3.

**Comment by ekarak** [comment]
First of all, I don't see a "setpoint" valueID which implies that your device is new and undocumented to the OpenZWave, hence not all command classes are available. 

Second,  this is the NodeJS adapter for OpenZWave, and my guess is that this is a question related to the code OpenZWave project. Can you try controlling your thermostat with MinOZW, the minimalist web server? 

Can you please [run this search](https://groups.google.com/forum/#!searchin/openzwave/danfoss$20devolo$20thermostat%7Csort:relevance) and locate if your device is known to OpenZWave?

Please reopen if this is an issue that relates to the NodeJS adapter, otherwise
