### ISSUE TITLE
[warn] [zwave] Error: libopenzwave.so.1.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Stephan35** [OpenZWave/node-red-contrib-openzwave#33]
Hello,
Sorry i do not know really where to post and get help.
I followed these instructions to install [openzwave for node-red ](https://www.npmjs.com/package/node-red-contrib-openzwave)

OpenZwave is correctly installed and compiled from git

As i understand , libopenzwave.so.1.4 is here "/usr/local/lib"

As i understand, i have to change path to tell where is libopenzwave.so.1.4 , maybe like this : 
Environment="LD_LIBRARY_PATH=/usr/local/lib"  [source](https://thefrinkiac7.wordpress.com/node-red/node-red-z-wave/)
But i do not really know how to : nodered.service does not exist.

Thanks to help and support.
Best regards.

**Comment by ekarak** [comment]
you need to run `sudo ldconfig -r` to refresh the dynamic libraries cache.
