### ISSUE TITLE
Add support for setting configuration values that aren't size 2

### ISSUE THREAD

**Issue by bparry** [OpenZWave/node-red-contrib-openzwave#34]
I can set many configuration parameters with topic:setValue and payload.cmdclass:112 if the size is 2. If the size isn't 2, then it doesn't seem to work. Could we expose the setConfigParam so we can set configurations that aren't just the default size? Or maybe we could a add an optional size parameter to the setValue call? (It seems like exposing setConfigParam would be easier)

**Comment by ekarak** [comment]
do you think you can fork the project and offer a PR? I don't have time currently.. It be at least early July before I pick this up
