### ISSUE TITLE
 Installation issue - node-red-openzwave-shared

### ISSUE THREAD

**Issue by Saschaya** [OpenZWave/node-red-contrib-openzwave#35]
Hello Ekarak,

Apparently, you are the author of the tutorial about open-zwave-shared for Red-Node. 

I meet the following issue:

https://github.com/npm/npm/issues/17517#issuecomment-312652006

Do you have explanations about it ?

Thank you in advance.

**Comment by ekarak** [comment]
thank you - I've updated the README. The package name was wrong :)
