### ISSUE TITLE
getNodeStatistics not returning results

### ISSUE THREAD

**Issue by tridiumcontrols** [OpenZWave/node-red-contrib-openzwave#37]
Hi, 

Thanks for this great work, no issues installing or setting up, got most of the z-wave nodes set up, want to get the node statistics from an node and z-wave out not returning results.

{"topic": "getNodeStatistics", "payload": {"args": [2]}}

Tried injecting the message via inject to z-wave IN, and  also tried sending the message through as a function, and z-wave out -> debug log is empty. 

Also, any way to dump all nodes inside the z-stick? I have over 15 nodes, and not sure what node # is what type of device. I have 10 smoke detectors, and 5 switches. Switches are easy to identify its the smoke detectors are sleeping and can't get the info I need to split the message.

**Comment by fraser73** [comment]
I've got the following code in a function node attached to a zwave out node and it works fine:

var returnMsg={"topic": "getNodeStatistics", "payload": {"args": [5]}};
return returnMsg;

You can also query the internal zwave global variable and return that:

var openzwaveNodes = global.get("openzwaveNodes");
return openzwaveNodes;

**Comment by TheVisionGuy** [comment]
I'm having a similar issue.  The getNodeStatistics call succeeds and outputs information to the console if full controller logging is enabled, but my ZWave nodes in my flow never see the same result.  The logged data indicates that the function is executing properly, but the message is never routed into the flow.

I have a side question: how do I know the current state of a switch at any given time? I am using logic to toggle a switch based on a sensors input and it woule be useful to know if the switch is already on or off.

**Comment by ekarak** [comment]
I believe the documentation covers this thouroughly:
```to get statistics from node 2 by using the getNodeStatistics() call:
{"topic": "getNodeStatistics", "payload": {"args": [2]}}

Most of the API calls in OpenZWave are asynchronous. This means that you don't get an immediate result value from the call itself, but you'll get notifications from their activity on the zwave-in input node. However, there are some direct API calls which do return a value (eg the getNodeStatistics is returning an object populated with the node's statistics: number of packets sent/received, transmission error counts etc).

In this case, the result is appended to the message payload and forwarded to the output of the ZWave-out node. This is the only message that the zwave-out node is emitting.```

As for your last question, I believe you can use the global nodes structure to get the state of your nodes:
```var openzwaveNodes = global.get("openzwaveNodes");```

Resolving
