### ISSUE TITLE
zwcfg_*.xml missing, Unhandled class error. 

### ISSUE THREAD

**Issue by tridiumcontrols** [OpenZWave/node-red-contrib-openzwave#38]
Is there a zwxfg_*xml that gets loaded when node-red starts this node? I.e. when I add zwave nodes through the addNode command, the zwave device gets added, info is flowing as expected, but upon restart of node-red, I wake up the battery powered zwave node, I get a unhandled class error. As if the device is missing from the cfg. 

Reason I bring up the 
zwcfg_*.xml is when OZWCP starts up it uses this file to restore configuration of the battery powered device and when I wake up the zwave device all info is restored and new events are shown, but not in node-red. 

My thought was to find the 
zwcfg_*.xml that node-red uses and symlink the one from OZWCP and have the devices show up in node-red and not get the unhandled class error.

I understand zwave library scans the zwave network and builds a database BUT if the battery device is sleeping then it doesn't get included as part of the scan and OZW is not sure what to do with it.

**Comment by dionmes** [comment]
I have the same issue, I don't see a zwcfg_*.xml being created ?

**Comment by ekarak** [comment]
Thanks for this!
I'm not sure if that's the correct place to do this however; the `close` event can happen on each NR redeployment and you really don't want to disconnect/reconnect on each reployment! OpenZWave takes a really long time (sometimes more than a minute!) to reinitialise.

**Comment by ekarak** [comment]
@dionmes can you please try out the following:
```js
  // ==========================
  function ZWaveController(cfg) {
    // ==========================
...
    /* =============== Node-Red events ================== */
    this.on("close", function() {
      log('full', 'zwave-controller: close');
      // write out zwcfg_homeid.xml to disk
      ozwDriver.writeConfig();
      // controller should also unbind from the C++ addon
      if (ozwDriver) ozwDriver.removeAllListeners();
    });
```

This will attempt to write out the config on each close/redeployment. Once you confirm this works I'll merge it to master.

**Comment by ekarak** [comment]
also have in mind that you can very easily write out the config file by issuing a message to the ZWave out node:

![image](https://user-images.githubusercontent.com/587817/32141502-d71022c0-bc8a-11e7-8890-586ad832e233.png)

**Comment by dionmes** [comment]
Hi, I will try it out. Good tip about the issuing a writeConfig, I might do this once a day to keep the config synced. As far as I can tell in my NR setup OZW always initialises on redeploy, it got faster after writing the config. I'll let you know when I changed the code.

**Comment by dionmes** [comment]
Ok. Tried the code out. Seems to be working fine. It does however not make any change to the zwave initialisation, but I think it is fine as it is. If you don't do a full redeploy on a change but just a modified nodes deploy it won't do a full zwave init.

**Comment by ekarak** [comment]
thank you, resolving

**Comment by triDcontrols** [comment]
Damn, my notifications have not been setup, sorry I missed all this action, I oepend a new issue not similar to this, I got the config to write, but now it's not being read on startup. 

https://github.com/OpenZWave/node-red-contrib-openzwave/issues/50
