### ISSUE TITLE
Not able to install package via npm command of via node-red "manage palette"

### ISSUE THREAD

**Issue by THM11** [OpenZWave/node-red-contrib-openzwave#39]
When I try to install this package, it fails due to following error:

Error: Command failed: npm install --save --save-prefix="~" --production node-red-contrib-openzwave@1.2.1
In file included from ../src/callbacks.cc:18:0:
../src/openzwave.hpp:29:21: fatal error: Manager.h: No such file or directory
 #include "Manager.h"
                     ^
compilation terminated.
make: *** [Release/obj.target/openzwave_shared/src/callbacks.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.41-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/openzwave-shared
gyp ERR! node -v v6.11.5
gyp ERR! n...

**Comment by ekarak** [comment]
As stated in the README page, you need to have the OpenZWave library *along with its headers* installed on your system.
