### ISSUE TITLE
Installation of module node-red-contrib-openzwave failed:

### ISSUE THREAD

**Issue by simatao** [OpenZWave/node-red-contrib-openzwave#40]
Hi, when trying to install the OpenZWave on NodeRed I get this error:

Error: Command failed: npm.cmd install --production node-red-contrib-openzwave
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
C:\Users\D060022\.node-red\node_modules\node-red-contrib-openzwave\node_modules\openzwave-shared\lib\install-ozw.js:147
  throw err;
  ^

Error: Can't find Python executable "python", you can set the PYTHON env variable.
    at Object.failNoPython (C:\Users\D060022\AppData\Local\Temp\ozwinstall-whfpd2bkjipgxxir4quxr\node_modules\node-gyp\lib\configure.js:483:19)
    at Object.<anonymous> (C:\Users\D060022\AppData\Local\Temp\ozwinstall-whfpd2bkjipgxxir4quxr\node_modules\node-gyp\lib\configure.js:508:16)
    at C:\Users\D060022\AppData\Local\Temp\ozwinstall-whfpd2bkjipgxxir4quxr\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:123...

**Comment by ekarak** [comment]
the Windows installation script for *openzwave-shared* needs *Python* to download and install OpenZWave.You'll probably also need a compiler toolchain. I don't use Windows, so sorry I can't help you much...
