### ISSUE TITLE
value-changed message doesn't match docs, nor include actual value

### ISSUE THREAD

**Issue by JoeStrout** [OpenZWave/node-red-contrib-openzwave#42]
The docs say that when a value changes on the Z-wave network, we should get a message like this:

```{ "topic":"zwave: value changed",
  "payload":{
    "nodeid":9,
    "cmdclass":37,
    "instance":1,
    "cmdidx":0,
    "oldState":false,
    "currState":true}}
```

But I'm getting (with a fresh build and install today) this:

```{"payload":{"nodeid":3,"nodeinfo":{"manufacturer":"GE","manufacturerid":"0x0063","product":"12722 On/Off Relay Switch","producttype":"0x4952","productid":"0x3032","type":"Binary Power Switch","name":"Office Lights","loc":""},"uuid":"b827ebbb5834-0xfe5d114a-3"}}```

This doesn't at all match the docs, and more importantly, doesn't contain any information about the actual value, making it fairly useless as far as I can see.

**Comment by ekarak** [comment]
are you sure this is in the  "zwave:value changed' topic? these should be emitted from the node discovery phase and should be under the 'zwave:node ready' (IIRC) topic. I'm resolving this, please reopen if you got a full message (incl. topic) that exhibits your claim.

**Comment by ekarak** [comment]
forgot to mention, please feel free to open up a pull request to extend the documentation :)
