### ISSUE TITLE
secured device - not decrypting message from device 

### ISSUE THREAD

**Issue by galley9** [OpenZWave/node-red-contrib-openzwave#47]
Hello Elias,
Thank you for the help getting node red OpenZwave up and running.  My node red Zwave nodes seem to be talking to the network.  

My network is basically the controller and two deadbolt locks.  Since they are security devices I had to enable the network key in options.xml.  I am getting this message in the node-red console when I manually open and close the locks.  The console shows initiating the key and does not show any errors.  Do you know if I need to use that key anywhere else?

Dec 13:29:18 - [info] OpenZwave: input: {"_msgid":"7039954f.4876fc","topic":"testNetworkNode","payload":{"args":[6]}}
22 Dec 13:29:18 - [info] OpenZwave: attempting direct API call to testNetworkNode()
22 Dec 13:29:18 - [info] OpenZwave: direct API call success, result=undefined
22 Dec 13:29:18 - [info] [debug:2fe2705a.2c17b]
{ args: [ 6 ] }
22 Dec 13:29:19 - [info] OpenZwave: node 6: Notification - NoOperation
22 Dec 13:29:19 - [info] OpenZwave: notification, args: {"nodeid":6,"notification":2,"help":"Notification - NoOperation"}
22 Dec 13:29:19 - [info] OpenZwave:       \==> 21b5a182.c6b53e event:notification
22 Dec 13:29:19 - [info] OpenZwave:       \==> a25db5c9.279ba8 event:notification
22 Dec 13:29:19 - [info] OpenZwave:       \==> dfcbf017.ec832 event:notification
22 Dec 13:29:19 - [info] [debug:2fe2705a.2c17b]
{ nodeid: 6,
notification: 2,
help: 'Notification - NoOperation',
uuid: 'b827eba0fa49-0xce75f5c1-6' }
2017-12-22 13:30:12.397 Warning, Node006, Failed to Decrypt Packet
2017-12-22 13:30:15.838 Warning, Node006, Failed to Decrypt Packet
2017-12-22 13:46:32.798 Warning, Node005, Failed to Decrypt Packet
2017-12-22 13:46:32.983 Warning, Node005, Failed to Decrypt Packet

Thank you for the help, Elias.
-bill

**Comment by dionmes** [comment]
Did you try the new version where you can put the security key in the zwave config node in node-red itself instead of the options.xml ?

**Comment by galley9** [comment]
I would love to.  I have 1.2.3 and see in, out and controller node in the palette manager.  I do not know how to access the dotted node "zwave-controller".  Is this where I put the security key?  If so how do I find it or use it.

Thanks,
-bill

**Comment by galley9** [comment]
I have found the configuration node and put in the security key.  The server console shows this loop when starting. 

> 2017-12-31 15:08:07.112 Always, OpenZwave Version 1.4.79 Starting Up
> 2017-12-31 15:08:07.113 Info, Setting Up Provided Network Key for Secure Communications
> 2017-12-31 15:08:07.113 Warning, Invalid Network Key. Does not contain 16 Bytes - Contains 1
> 2017-12-31 15:08:07.114 Warning, Raw Key: 0x96
> 2017-12-31 15:08:07.114 Warning, Parsed Key:
> 2017-12-31 15:08:07.114 Warning, 1) - 0x96
> 2017-12-31 15:08:07.115 Error, Exception: Driver.cpp:6727 - 103 - Failed to Read Network Key
> Error: Driver.cpp:6727 - Failed to Read Network Key
> nodered.service: main process exited, code=exited, status=103/n/a
> Unit nodered.service entered failed state.
> nodered.service holdoff time over, scheduling restart.
> Stopping Node-RED graphical event wiring tool....
> Starting Node-RED graphical event wiring tool....
> Started Node-RED graphical event wiring tool..
> Stopping Node-RED graphical event wiring tool....
> Stopped Node-RED graphical event wiring tool..




I will try to find the key and delete it so I can start the node-red server.  I put the network key in this way: 0x00, 0x00,...  What is the correct format for the security key?

Thanks,
-bill

**Comment by galley9** [comment]
My goal was to get this working this year.  The key is working!   I think I have everything installed and talking.  Now, I do not know how to use it.  Can you give me a reference as to how to control the nodes?  I have a zwave door lock and I have no idea as to what the inject (payload) should look like. I know the zwave node ID, Command Class and probably anything else I can find out.  I just do not know what or how to communicate to the node.

Thanks,
-bill

**Comment by dionmes** [comment]
Hi, great that it is working and a happy new year. This node-red zwave is actually an implementation of [https://github.com/OpenZWave/node-openzwave-shared](url) . So you can use the commands and events described in the node-openzwave-shared documentation to control your zwave devices. I haven't used it myself but maybe this flow could make it easier : [https://flows.nodered.org/flow/41ae75dbfbe6465d5cf40248e2500e0a](url)

**Comment by galley9** [comment]
I would like to thank both of you for your hard work building and supporting the zwave node-red nodes.  I would also like to thank you for getting me up and running.  I am happy to report everything is working like a charm.  I had no idea how much overhead was involved with the zwave protocol.  Have a great new year and keep up the good work.
