### ISSUE TITLE
How do I discover, pair and add a zwave node to node red?

### ISSUE THREAD

**Issue by MarkSwanson** [OpenZWave/node-red-contrib-openzwave#48]
I have node-red installed, and I have the zwave in and zwave out nodes configured (status is 'connected').  The logs show /dev/zwave is found just fine.

However, I'm having trouble with pairing/inclusion using a Nortek / gocontrol HUSBZB-1.
(I wanted the ability to also use zigbee devices).

I actually have an Aeotec, and inclusion works with that just fine.

I was hoping someone could point me to some documentation about how to do pairing/inclusion with the HUSBZB-1.

Thanks!

**Comment by dionmes** [comment]
You have to create your own nodes to control zwave by sending commands and receiving events, or you can try [ https://flows.nodered.org/flow/41ae75dbfbe6465d5cf40248e2500e0a](url) . For documentation on commands and events look at : [https://github.com/OpenZWave/node-openzwave-shared](url) as node-red-contrib-openzwave is kind of a wrapper around node-openzwave.

**Comment by ekarak** [comment]
Mark I'm closing this issue. Please use the chatroom for usage questions, this looks to be a compatibility issue with that HUSBZB controller. Have you used another OpenZWave app (eg the control panel) to pair devices? if you have, please reopen this with extra logs showing that the some API usage is wrong or missing or buggy etc etc.
Thanks
