### ISSUE TITLE
Problems with door lock

### ISSUE THREAD

**Issue by Mastiffen** [OpenZWave/node-red-contrib-openzwave#49]
Hi! I have an ID Lock with Z-Wave module, and I have added it securely via Open Zwave Control Panel. I can also open and close it with the OZCP. But when I try in Node-RED, it just doesn't work. I get feedback into Node-RED when I open or close the lock manually. The code I'm trying to use to open is this:

`msg = {topic: 'setValue', payload: {"nodeid":3, "cmdclass":98, "cmdidx":0, "instance":1, "value":false}};
return msg;`

But what I get in Node-RED after about 10 seconds is:

{"nodeid":3,"notification":1,"help":"Notification - TimeOut","uuid":"b827eb96e3ae-0xc2106156-3"}

I believe that should be the correct code. I have tried several other versions, but none have worked. I have upped the ThreadTerminateTimeout to 25 seconds, and now when Node-RED starts up, I get this (which I also see in the console after about 15 seconds when trying to send a command): 

> 2018-01-07 17:12:43.665 Error, Node003, ERROR: Dropping command,
expected response not received after 1 attempt(s)

Before I upped the timeout, the console didn't say anything on startup. Seems like a polling to the lock is not working or something. Do you have any idea what this can be?

**Comment by Mastiffen** [comment]
I have tried to remove the door lock from the Z-Stick, do a hard reset on the stick, and then add it again. I also changed the options.xml network key format to the same as Node-RED needs, so without the spaces. That did not stop me from adding the lock again in OZWCP. But I did get some slightly different results in the logger. Here's a full log of me trying to open the lock:

> 9 Jan 09:25:04 - [info] OpenZwave: input:
{"topic":"setValue","payload":{"nodeid":2,"cmdclass":98,"cmdidx":0,"instance":1,"value":false},"_msgid":"f82b0c38.d8615"}
9 Jan 09:25:04 - [info] OpenZwave: ZWaveOut.setValue payload:
{"nodeid":2,"cmdclass":98,"cmdidx":0,"instance":1,"value":false}
2018-01-09 09:25:14.461 Error, Node002, ERROR: Dropping command,
expected response not received after 1 attempt(s)
9 Jan 09:25:14 - [info] OpenZwave: node 2: Notification - TimeOut
9 Jan 09:25:14 - [info] OpenZwave: notification, args:
{"nodeid":2,"notification":1,"help":"Notification - TimeOut"}
9 Jan 09:25:14 - [info] OpenZwave: 	\==> 4e4fd84.0ebc128
event:notification
9 Jan 09:25:14 - [info] OpenZwave: 	\==> 2000b7c7.9eb7e
event:notification
9 Jan 09:25:14 - [info] OpenZwave: 	\==> f2891d34.60ff8
event:notification
9 Jan 09:25:17 - [info] OpenZwave: zwave node 2: changed:
98:Locked:false ->
"{\"value_id\":\"2-98-1-0\",\"node_id\":2,\"class_id\":98,\"type\":\"bool\",\"genre\":\"user\",\"instance\":1,\"index\":0,\"label\":\"Locked\",\"units\":\"\",\"help\":\"\",\"read_only\":false,\"write_only\":false,\"min\":0,\"max\":0,\"is_polled\":false,\"value\":false}"
9 Jan 09:25:17 - [info] OpenZwave: value changed, args:
{"nodeid":2,"cmdclass":98,"cmdidx":0,"instance":1,"oldState":false,"currState":false,"label":"Locked","units":"","value":{"value_id":"2-98-1-0","node_id":2,"class_id":98,"type":"bool","genre":"user","instance":1,"index":0,"label":"Locked","units":"","help":"","read_only":false,"write_only":false,"min":0,"max":0,"is_polled":false,"value":false}}
9 Jan 09:25:17 - [info] OpenZwave: 	\==> 4e4fd84.0ebc128
event:value changed
9 Jan 09:25:17 - [info] OpenZwave: 	\==> 2000b7c7.9eb7e
event:value changed
9 Jan 09:25:17 - [info] OpenZwave: 	\==> f2891d34.60ff8
event:value changed
9 Jan 09:25:17 - [info] OpenZwave: zwave node 2: changed: 98:Locked
(Advanced):Unsecure ->
"{\"value_id\":\"2-98-1-1\",\"node_id\":2,\"class_id\":98,\"type\":\"list\",\"genre\":\"user\",\"instance\":1,\"index\":1,\"label\":\"Locked
(Advanced)\",\"units\":\"\",\"help\":\"\",\"read_only\":false,\"write_only\":false,\"min\":0,\"max\":0,\"is_polled\":false,\"values\":[\"Unsecure\",\"Unsecured
with Timeout\",\"Inside Handle Unsecured\",\"Inside Handle Unsecured
with Timeout\",\"Outside Handle Unsecured\",\"Outside Handle Unsecured
with Timeout\",\"Secured\",\"Invalid\"],\"value\":\"Unsecure\"}"
9 Jan 09:25:17 - [info] OpenZwave: value changed, args:
{"nodeid":2,"cmdclass":98,"cmdidx":1,"instance":1,"oldState":"Unsecure","currState":"Unsecure","label":"Locked
(Advanced)","units":"","value":{"value_id":"2-98-1-1","node_id":2,"class_id":98,"type":"list","genre":"user","instance":1,"index":1,"label":"Locked
(Advanced)","units":"","help":"","read_only":false,"write_only":false,"min":0,"max":0,"is_polled":false,"values":["Unsecure","Unsecured
with Timeout","Inside Handle Unsecured","Inside Handle Unsecured with
Timeout","Outside Handle Unsecured","Outside Handle Unsecured with
Timeout","Secured","Invalid"],"value":"Unsecure"}}
9 Jan 09:25:17 - [info] OpenZwave: 	\==> 4e4fd84.0ebc128
event:value changed
9 Jan 09:25:17 - [info] OpenZwave: 	\==> 2000b7c7.9eb7e
event:value changed
9 Jan 09:25:17 - [info] OpenZwave: 	\==> f2891d34.60ff8
event:value changed
9 Jan 09:25:18 - [info] OpenZwave: input:
{"topic":"setValue","payload":{"nodeid":2,"cmdclass":98,"cmdidx":0,"instance":1,"value":true},"_msgid":"dfc8a6e0.b6bba8"}
9 Jan 09:25:18 - [info] OpenZwave: ZWaveOut.setValue payload:
{"nodeid":2,"cmdclass":98,"cmdidx":0,"instance":1,"value":true}
9 Jan 09:25:20 - [info] OpenZwave: zwave node 2: changed: 113:Alarm
Type:0 ->
"{\"value_id\":\"2-113-1-0\",\"node_id\":2,\"class_id\":113,\"type\":\"byte\",\"genre\":\"user\",\"instance\":1,\"index\":0,\"label\":\"Alarm
Type\",\"units\":\"\",\"help\":\"\",\"read_only\":true,\"write_only\":false,\"min\":0,\"max\":255,\"is_polled\":false,\"value\":0}"
9 Jan 09:25:20 - [info] OpenZwave: value changed, args:
{"nodeid":2,"cmdclass":113,"cmdidx":0,"instance":1,"oldState":0,"currState":0,"label":"Alarm
Type","units":"","value":{"value_id":"2-113-1-0","node_id":2,"class_id":113,"type":"byte","genre":"user","instance":1,"index":0,"label":"Alarm
Type","units":"","help":"","read_only":true,"write_only":false,"min":0,"max":255,"is_polled":false,"value":0}}
9 Jan 09:25:20 - [info] OpenZwave: 	\==> 4e4fd84.0ebc128
event:value changed
9 Jan 09:25:20 - [info] OpenZwave: 	\==> 2000b7c7.9eb7e
event:value changed
9 Jan 09:25:20 - [info] OpenZwave: 	\==> f2891d34.60ff8
event:value changed
9 Jan 09:25:20 - [info] OpenZwave: zwave node 2: changed: 113:Alarm
Level:0 ->
"{\"value_id\":\"2-113-1-1\",\"node_id\":2,\"class_id\":113,\"type\":\"byte\",\"genre\":\"user\",\"instance\":1,\"index\":1,\"label\":\"Alarm
Level\",\"units\":\"\",\"help\":\"\",\"read_only\":true,\"write_only\":false,\"min\":0,\"max\":255,\"is_polled\":false,\"value\":0}"
9 Jan 09:25:20 - [info] OpenZwave: value changed, args:
{"nodeid":2,"cmdclass":113,"cmdidx":1,"instance":1,"oldState":0,"currState":0,"label":"Alarm
Level","units":"","value":{"value_id":"2-113-1-1","node_id":2,"class_id":113,"type":"byte","genre":"user","instance":1,"index":1,"label":"Alarm
Level","units":"","help":"","read_only":true,"write_only":false,"min":0,"max":255,"is_polled":false,"value":0}}
9 Jan 09:25:20 - [info] OpenZwave: 	\==> 4e4fd84.0ebc128
event:value changed
9 Jan 09:25:20 - [info] OpenZwave: 	\==> 2000b7c7.9eb7e
event:value changed
9 Jan 09:25:20 - [info] OpenZwave: 	\==> f2891d34.60ff8
event:value changed
9 Jan 09:25:20 - [info] OpenZwave: zwave node 2: changed:
113:SourceNodeId:0 ->
"{\"value_id\":\"2-113-1-2\",\"node_id\":2,\"class_id\":113,\"type\":\"byte\",\"genre\":\"user\",\"instance\":1,\"index\":2,\"label\":\"SourceNodeId\",\"units\":\"\",\"help\":\"\",\"read_only\":true,\"write_only\":false,\"min\":0,\"max\":255,\"is_polled\":false,\"value\":0}"
9 Jan 09:25:20 - [info] OpenZwave: value changed, args:
{"nodeid":2,"cmdclass":113,"cmdidx":2,"instance":1,"oldState":0,"currState":0,"label":"SourceNodeId","units":"","value":{"value_id":"2-113-1-2","node_id":2,"class_id":113,"type":"byte","genre":"user","instance":1,"index":2,"label":"SourceNodeId","units":"","help":"","read_only":true,"write_only":false,"min":0,"max":255,"is_polled":false,"value":0}}
9 Jan 09:25:20 - [info] OpenZwave: 	\==> 4e4fd84.0ebc128
event:value changed
9 Jan 09:25:20 - [info] OpenZwave: 	\==> 2000b7c7.9eb7e
event:value changed
9 Jan 09:25:20 - [info] OpenZwave: 	\==> f2891d34.60ff8
event:value changed
9 Jan 09:25:20 - [info] OpenZwave: zwave node 2: changed: 113:Access
Control:1 ->
"{\"value_id\":\"2-113-1-9\",\"node_id\":2,\"class_id\":113,\"type\":\"byte\",\"genre\":\"user\",\"instance\":1,\"index\":9,\"label\":\"Access
Control\",\"units\":\"\",\"help\":\"\",\"read_only\":true,\"write_only\":false,\"min\":0,\"max\":255,\"is_polled\":false,\"value\":1}"
9 Jan 09:25:20 - [info] OpenZwave: value changed, args:
{"nodeid":2,"cmdclass":113,"cmdidx":9,"instance":1,"oldState":1,"currState":1,"label":"Access
Control","units":"","value":{"value_id":"2-113-1-9","node_id":2,"class_id":113,"type":"byte","genre":"user","instance":1,"index":9,"label":"Access
Control","units":"","help":"","read_only":true,"write_only":false,"min":0,"max":255,"is_polled":false,"value":1}}
9 Jan 09:25:20 - [info] OpenZwave: 	\==> 4e4fd84.0ebc128
event:value changed
9 Jan 09:25:20 - [info] OpenZwave: 	\==> 2000b7c7.9eb7e
event:value changed
9 Jan 09:25:20 - [info] OpenZwave: 	\==> f2891d34.60ff8
event:value changed
9 Jan 09:25:21 - [info] OpenZwave: zwave node 2: changed:
98:Locked:false ->
"{\"value_id\":\"2-98-1-0\",\"node_id\":2,\"class_id\":98,\"type\":\"bool\",\"genre\":\"user\",\"instance\":1,\"index\":0,\"label\":\"Locked\",\"units\":\"\",\"help\":\"\",\"read_only\":false,\"write_only\":false,\"min\":0,\"max\":0,\"is_polled\":false,\"value\":true}"
9 Jan 09:25:21 - [info] OpenZwave: value changed, args:
{"nodeid":2,"cmdclass":98,"cmdidx":0,"instance":1,"oldState":false,"currState":true,"label":"Locked","units":"","value":{"value_id":"2-98-1-0","node_id":2,"class_id":98,"type":"bool","genre":"user","instance":1,"index":0,"label":"Locked","units":"","help":"","read_only":false,"write_only":false,"min":0,"max":0,"is_polled":false,"value":true}}
9 Jan 09:25:21 - [info] OpenZwave: 	\==> 4e4fd84.0ebc128
event:value changed
9 Jan 09:25:21 - [info] OpenZwave: 	\==> 2000b7c7.9eb7e
event:value changed
9 Jan 09:25:21 - [info] OpenZwave: 	\==> f2891d34.60ff8
event:value changed
9 Jan 09:25:22 - [info] OpenZwave: zwave node 2: changed:
98:Locked:true ->
"{\"value_id\":\"2-98-1-0\",\"node_id\":2,\"class_id\":98,\"type\":\"bool\",\"genre\":\"user\",\"instance\":1,\"index\":0,\"label\":\"Locked\",\"units\":\"\",\"help\":\"\",\"read_only\":false,\"write_only\":false,\"min\":0,\"max\":0,\"is_polled\":false,\"value\":true}"
9 Jan 09:25:22 - [info] OpenZwave: value changed, args:
{"nodeid":2,"cmdclass":98,"cmdidx":0,"instance":1,"oldState":true,"currState":true,"label":"Locked","units":"","value":{"value_id":"2-98-1-0","node_id":2,"class_id":98,"type":"bool","genre":"user","instance":1,"index":0,"label":"Locked","units":"","help":"","read_only":false,"write_only":false,"min":0,"max":0,"is_polled":false,"value":true}}
9 Jan 09:25:22 - [info] OpenZwave: 	\==> 4e4fd84.0ebc128
event:value changed
9 Jan 09:25:22 - [info] OpenZwave: 	\==> 2000b7c7.9eb7e
event:value changed
9 Jan 09:25:22 - [info] OpenZwave: 	\==> f2891d34.60ff8
event:value changed

**Comment by Mastiffen** [comment]
I have no idea why, but I just tested a version of the same code for a second time, and now it works! So the code in Node-RED that works is this:

`msg = {"topic": "setValue", "payload": {"nodeid":2, "cmdclass":98, "cmdidx":0, "instance":1, "value":false}};
return msg;
`

And it seems like what actually got this working was to remove spaces in the network key in Open-zwave.

**Comment by 0rsa** [comment]
Exactly same issue with same topic/payload and it does not work
Using OZW Control Panel, it works fine.
Node has been included securely.
Network key is fine without blank space.
Node state is correctly refreshed using node red but I cannot send a command which works.

I got all the time the same error: "Notification - TimeOut"

Update:
It works after deleting /path/to/.node-red/ozwcache_xxxxxx.xml and restarting node red. Openzwave did a resync of this file and it finally works.
