### ISSUE TITLE
What git repo should be used?

### ISSUE THREAD

**Issue by pastukhov** [OpenZWave/node-red-contrib-openzwave#5]
Just to be clear

**Comment by ekarak** [comment]
I think any existing links to ekarak/node-red-contrib-openzwave should work as they are, redirected to OpenZWave/ now. Are you having problems?

**Comment by ekarak** [comment]
Hi Artem,
I think that git servers automatically make the redirection to the new location, so there's no issue with changing paths:
```
ekarakou@amnesia:~/src/node-openzwave-shared (master)$ git push
Counting objects: 15, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.11 KiB | 0 bytes/s, done.
Total 8 (delta 7), reused 0 (delta 0)
remote: This repository moved. Please use the new location:
remote:   https://github.com/OpenZWave/node-openzwave-shared.git
To git@github.com:ekarak/node-openzwave-shared.git
   a7fda29..e0008cb  master -> master
ekarakou@Pal4opb01:~/src/node-openzwave-shared (master)$
```

I've changed the references in all `package.json` files to point to the correct location, so an `npm update` would make these warnings disappear.

closing this call.
