### ISSUE TITLE
battery powered zwave devices not working after node-red reboot, used writeconfig command

### ISSUE THREAD

**Issue by triDcontrols** [OpenZWave/node-red-contrib-openzwave#50]
Hi, 

I have a smoke detector that is battery powered and after successful add thorough this function 
 ```
msg = {"topic": "addNode", "payload": {"prependHomeId": true}}
 return msg;
```
 the smoke detector works just fine on initial add, I see debug all info is there while node-red is running, tested smoke detector few times, and values come in just fine, I went ahead and sent a `writeConfig` topic to zwave node out, which I do see that zwcfg_xxx.xml has been changed by running `ls -la` command and opening the zwcfg_xxx.xml with nano, I do see that the smoke detector is listed and command calsses are defined, I went ahead and rebooted node-red, then tested smoke detector again and nothing happened in the debug. I checked the zwcfg_xxx.xml and smoke detector is listed, it's almost as if the zwcfg_xxx.xml config isn't being read during startup, I thought it was a permissions issue, I changed zwcfg_xxx.xml to chmod 777 and still nothing, where do I go to troubleshoot this further?

here is the node-red startup. 

```
0|node-red | 15 Feb 11:18:55 - [info] Polymer started at /polymer
0|node-red | 15 Feb 11:18:55 - [info] Dashboard version 2.8.0 started at /ui
0|node-red | 15 Feb 11:18:56 - [warn] ------------------------------------------------------
0|node-red | 15 Feb 11:18:56 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
0|node-red | 15 Feb 11:18:56 - [warn] ------------------------------------------------------
0|node-red | 15 Feb 11:18:56 - [info] Settings file  : /home/usermd/.node-red/settings.js
0|node-red | 15 Feb 11:18:56 - [info] User directory : /home/usermd/.node-red
0|node-red | 15 Feb 11:18:56 - [info] Flows file     : /home/usermd/.node-red/flows_node-red.json
0|node-red | 15 Feb 11:18:56 - [info] Server now running at http://127.0.0.1:1880/
0|node-red | 15 Feb 11:18:56 - [info] Starting flows
0|node-red | Initialising OpenZWave 1.4.0 binary addon for Node.JS.
0|node-red | 	OpenZWave Security API is ENABLED
0|node-red | 	ZWave device db    : /usr/local/etc/openzwave
0|node-red | 	User settings path : /home/usermd/.node-red
0|node-red | 	Option Overrides : --Logging true --ConsoleOutput true --QueueLogLevel 6 --DriverMaxAttempts 3 --NetworkKey 
0|node-red | 2018-02-15 11:18:56.878 Always, OpenZwave Version 1.4.0 Starting Up
0|node-red | 2018-02-15 11:18:56.878 Warning, Failed - Network Key Not Set
0|node-red | 15 Feb 11:18:56 - [info] OpenZwave: zwave-controller subscribed to "driver failed"
0|node-red | 15 Feb 11:18:56 - [info] OpenZwave: zwave-controller subscribed to "scan complete"
0|node-red | 2018-02-15 11:18:56.893 Error, ERROR: Cannot get exclusive lock for serial port /dev/ttyACM0. Error code 11
0|node-red | 15 Feb 11:18:57 - [info] Started flows

```

**Comment by triDcontrols** [comment]
tried bunch of stuff and still can't get battery powered devices to work after node-red restart.

1) added node from node-red
2) added node from ozwcp and transfered the zwcp_xxx.xml file 
3) deleted node from node-red, 
4) deleted node-red ozwcp
5) re did all the above steps, 
6) chowned and chmod the zwcfg_xxx.xml to root:root with 777 permissions
7) tried started node-red with just node-red in terminal without pm2 auto-start manager
8) deleted the zwcfg and restarted all over again

I

**Comment by triDcontrols** [comment]
Ended up using home assistant for the smoke detectors until I can get this issue resolved.

**Comment by ekarak** [comment]
this should have been solved with release 1.2.4 which defaults the `UserPath` configuration directory to Node Red's own config path.

**Comment by Tokter** [comment]
I'm having the exact same problem as triDcontrols, my battery powered tilt sensor only starts working if I trigger a wake-up notification by opening the case. After restarting node-red, it stops working. I don't think 1.2.4 fixed that issue...

**Comment by Fishwaldo** [comment]
Thats expected with the way z-wave battery powered devices work and OZW.
