### ISSUE TITLE
Installed without errors but no new nodes available

### ISSUE THREAD

**Issue by patrickjane** [OpenZWave/node-red-contrib-openzwave#51]
I installed `OpenZWave library` on my raspberry pi (raspbian stretch), and afterwards ran 

```
$ cd ~/.node-red
$ npm install node-red-contrib-openzwave
```

I get no errors, but after restarting node-red I see no new nodes, so I have no idea whats going wrong.

Also, I am a bit confused by  

> You can do that by using writeConfig() to store that XML file whenever you add/edit/remove nodes.

Is there a better explanation for this? I have no clue what I should do.

[edit] node-red version 0.18.2, node version v8.9.4.

**Comment by robertsLando** [comment]
+ 1, same error here, node-red version 18.0.4.

**Comment by robertsLando** [comment]
FIXED: Run this comand to update shared libraries cahe:

`sudo ldconfig` 

Stop and restart node, now z-wave nodes should be shown in node palette

**Comment by ekarak** [comment]
resolving
