### ISSUE TITLE
Node-red crashes after installation

### ISSUE THREAD

**Issue by realsquash** [OpenZWave/node-red-contrib-openzwave#52]
I installed this today on a Raspbian Stretch image.  The prereqs and this contrib both installed without any problems.  I restarted NR once to refresh everything and the two nodes appeared in the list.  I dragged one over into a new flow and went into the config and picked the wrong serial port and deployed.  Five seconds later NR became unresponsive.  I restarted NR and it started fine until it tried to talk to the port, which was about 5 seconds.  I managed to get that node out and deploy after a few tries and now everything runs fine with the correct serial port specified.  Maybe it would be good to just put a check in there somewhere so NR can keep running with the invalid config?

**Comment by thucar** [comment]
This would be awesome.

**Comment by NewYor** [comment]
Had the same problem. Node-Red is built with stability in mind. So should nodes.

**Comment by nospam2k** [comment]
I also had the same problem. I think zwaveController needs some more error handling.

**Comment by ekarak** [comment]
this will be addressed in the next release, I replaced process.exit() with a log message.
