### ISSUE TITLE
Add parameter to manually set device configuration DB

### ISSUE THREAD

**Issue by robertsLando** [OpenZWave/node-red-contrib-openzwave#57]
My Z-Wave device was not in the open-zwave db so I have added the xml configuration file and added the entry to `manufacturer_specific.xml` file (the default db path is `/usr/local/etc/openzwave/`)
I can correctly see it working in `open-zwave-control-panel` but I'm not able to see it working using the node red node. When node is ready `nodeinfo` property looks like:

```json
nodeinfo: {
	"manufacturer":"Thermo-Floor (Heatit)",
	"manufacturerid":"0x019b",
	"product":"Unknown:type=0003,id=0202",
	"producttype":"0x0003",
	"productid":"0x0202",
	"type":"",
	"name":"",
	"loc":""
}
```

Firstly I would like to ask you if it is possible to add a configuration option where I can set the z-wave db path manually instead of using the default one than I would ask you why my device is still not recognized from this node but it is from control panel even if they are using the same configuration db folder?

The `manufacturer_specific.xml` has this entry correctly set: 

```xml
<Manufacturer id="019b" name="ThermoFloor AS">
		<Product type="0001" id="0001" name="Heatit Thermostat TF 021" config="thermofloor/heatit021.xml"/>
		<Product type="0003" id="0202" name="Heatit Thermostat Z-TRM2" config="thermofloor/heatitztrm2.xml"/>
</Manufacturer>
```

and there is the file `heatitztrm2.xml` in `thermofloor` folder inside `config` folder.

I think the node uses something cached and doesn't loads the new devices config db changes. Is this possible? I have also tried to uninstall both openzwave-shared and node-red-contrib-openzwave but nothing has happen. Any suggestions? 

Thanks

**Comment by dionmes** [comment]
I think you should address this with the node-openzwave-shared library and maybe even the openzwave-lib itself. Node-red-contrib-openzwave is just the interface to those libraries.

**Comment by ekarak** [comment]
@dionmes , @robertsLando I will add the option to override the ZWave device db path, it needs to be added here: https://github.com/OpenZWave/node-red-contrib-openzwave/blob/master/10-zwave.js#L358

**Comment by dionmes** [comment]
That is the quick fix for using it only with node-red. The correct way should be to add it to the openzwave lib device db so you have a system-wide correct device lib (and for others if the device gets accepted).

**Comment by robertsLando** [comment]
I have already edited the code of the node to accept a custom device db path, I have added a settings in node red settings called zwaveDB, if not present the default device db would be used, this could be made more easy by adding an entry in configuration node. 

About my problem: I had to reset my controller, exclude and include the unknown device than he has found his configuration correctly

**Comment by ekarak** [comment]
closing old issue
