### ISSUE TITLE
 undefined symbol error

### ISSUE THREAD

**Issue by ngocgl** [OpenZWave/node-red-contrib-openzwave#58]
hi!

My NR fail right after I start OpenZwarve node with follow error in log:

23 Jun 16:14:03 - [info] Starting flows
23 Jun 16:14:03 - [info] Started flows
23 Jun 16:14:03 - [info] Server now running at http://127.0.0.1:1880/
23 Jun 16:14:22 - [info] Stopping modified flows
23 Jun 16:14:22 - [info] Stopped modified flows
23 Jun 16:14:22 - [info] Starting modified flows
Initialising OpenZWave 1.4.79 binary addon for Node.JS.
        OpenZWave Security API is ENABLED
        ZWave device db    : /usr/local/etc/openzwave/
        User settings path : /home/pi/.node-red
        Option Overrides : --Logging true --ConsoleOutput true --QueueLogLevel 6 --DriverMaxAttempts 3 --NetworkKey
node-red: symbol lookup error: /home/pi/.node-red/node_modules/openzwave-shared/build/Release/openzwave_shared.node: undefined symbol: _ZN9OpenZWave7Options6CreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_S8_

**Comment by dionmes** [comment]
Looks like an issue between the openzwave lib and node-openzwave-shared .

**Comment by ngocgl** [comment]
I spent two days to debug but got no luck.

**Comment by ngocgl** [comment]
hi ekarak!

Please guide me to fix it.

**Comment by dionmes** [comment]
Clean up your current install (remove openzwave, node-openzwave-shared). And follow the installation on this page; [https://github.com/OpenZWave/node-openzwave-shared](url)

**Comment by ekarak** [comment]
closing old ticket
