### ISSUE TITLE
Installation instructions incomplete or incorrect

### ISSUE THREAD

**Issue by maxwellhadley** [OpenZWave/node-red-contrib-openzwave#6]
Please add a full description of how to install everything, from scratch, required to install this node in node-red. I get this error:

    > openzwave-shared@1.0.0 install /usr/local/lib/node_modules/node-red-contrib-    openzwave/node_modules/openzwave-shared
    > node-gyp rebuild

    make: Entering directory `/usr/local/lib/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared/build'
      CXX(target) Release/obj.target/openzwave_shared/src/openzwave.o
    In file included from ../src/openzwave.cc:18:0:
    ../src/openzwave.hpp:30:21: fatal error: Manager.h: No such file or directory
     #include "Manager.h"
                         ^
    compilation terminated.
    make: *** [Release/obj.target/openzwave_shared/src/openzwave.o] Error 1

It looks like I'm missing a library header file, but how do I install this? I'm running kubuntu 14.04 on i386

**Comment by ekarak** [comment]
Hi Max,

Seems like the OpenZWave library isn't installed in your system. Precompiled packages for installing this easily can be found at http://old.openzwave.com/downloads/  (be sure to install BOTH the library and its "-dev" development package!)
For example for 64-bit Ubuntu 14.04 you would need to download and install everything under:
http://mirror.my-ho.st/Downloads/OpenZWave/xUbuntu_14.04/amd64/
You'll find more details on the OpenZWave binding in this link:
- https://www.npmjs.com/package/openzwave-shared  

Thanks!

**Comment by ekarak** [comment]
Correction since you're on i386 the correct link is 
http://mirror.my-ho.st/Downloads/OpenZWave/xUbuntu_14.04/i386/

**Comment by maxwellhadley** [comment]
OK that worked. I downloaded the three i386 .deb packages from the xubuntu 14.04 directory on the openzwave.com server, then installed them using 'sudo dpkg -i deb-file-name.deb', starting with the library, then the -dev library, then the openzwave package itself. The I could install the node-red-contrib-openzwave package. Many thanks!
This could do with being spelled out in the README file, though.

**Comment by ekarak** [comment]
Hi Max, thanks for your suggestions. I've just updated the documentation so that the 'Installation' section points to the required dependencies for 'node-openzwave-shared'

Thanks again,
Elias
