### ISSUE TITLE
Remove process.exit() call

### ISSUE THREAD

**Issue by sja** [OpenZWave/node-red-contrib-openzwave#63]
I think it's a bit drastic to exit the whole process in case ZWave Controller could not be initialized. (https://github.com/OpenZWave/node-red-contrib-openzwave/blob/master/10-zwave.js#L154)

In my case, I move the installation from one to another host where the USB stick has another device string (`/dev/tty...`). With that, I was not able to start Node RED with my existing flow to fix it. It was just shutted down by that line.

My Workaround was to comment that Line 154 in `node_modules/node-red-contrib-openzwave/10-zwave.js`.

**Comment by ekarak** [comment]
https://github.com/OpenZWave/node-red-contrib-openzwave/commit/5af6572a0cf76fed81ca0b1f8f07af8644e56d64
Will release this shortly
