### ISSUE TITLE
Problem installing on Mac OSX Mojave

### ISSUE THREAD

**Issue by MarkAtmos** [OpenZWave/node-red-contrib-openzwave#68]
I am having a problem installing node-red-contrib-openzwave with the following output:

> openzwave-shared@1.5.1 preinstall /Users/*/.node-red/node_modules/openzwave-shared
> node lib/install-ozw.js

> openzwave-shared@1.5.1 install /Users/*/.node-red/node_modules/openzwave-shared
> node-gyp rebuild

/bin/sh: ldconfig: command not found
gyp: Call to 'ldconfig -p | grep 'libopenzwave.so ' | awk '{print $4}' | xargs nm -g --demangle |grep OpenZWave::Value::GetTypeNameFromEnum | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/*/.node-red/node_modules/openzwave-shared
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*/.npm/_logs/2019-06-26T23_42_43_311Z-debug.log

I had a similar problem installing node-openzwave-shared which this fixed: https://github.com/OpenZWave/node-openzwave-shared/issues/308

**Comment by ekarak** [comment]
closing old tickets.
