### ISSUE TITLE
How to get battery level?

### ISSUE THREAD

**Issue by Qaldak** [OpenZWave/node-red-contrib-openzwave#71]
would like to get the battery level of my zwave device weekly. But I couldn't find the exact command for this.

Here the JSON:
```
{
	"topic":"???",
	"payload": {
		"nodeid":4,
		"cmdclass":128
	}
}

```
which topic I have to use? I didn't found in OpenZWave::Manager...
cmdclass "128" = COMMAND_CLASS_BATTERY

Maybe anyone got the solution for this.
thx.

**Comment by Qaldak** [comment]
I tried with followin code:
```
{
"topic":"refreshValue",
"payload": {"arg":[4,128,1,0]}
}
```

But I don't receive any event on this.

I discussed my issue also here: https://discourse.nodered.org/t/get-device-battery-level-zwave/14273/7

It seems on my Raspi I don't have any zwcfg_xxx.xml file. I just get an ozwcache_xxx.xml.
Do I need the zwcfg_xxx.xml to send events to my RazBerry?

All other zwave-events like motion detection, tamper, illumination or temperature works.

**Comment by Qaldak** [comment]
Following solutions did not work:
> 
> 
> also have in mind that you can very easily write out the config file by issuing a message to the ZWave out node:
> 
> ![image](https://user-images.githubusercontent.com/587817/32141502-d71022c0-bc8a-11e7-8890-586ad832e233.png)


> 
> 
> Checking this, solved the issue for me:
> ![image](https://user-images.githubusercontent.com/3439101/40036556-f6048f86-57bc-11e8-8480-a45787b15e37.png)

**Comment by ekarak** [comment]
This issue tracker is not meant for usage questions.

You can't request a battery-powered device to report its status, because it would have to keep its radio on, and thus consume its battery. Instead, the device will report periodically (once a day perhaps) its battery status and you need to have a listener for any updates from this node to capture this information.
