### ISSUE TITLE
Seconds switch of Fibaro FGS-223 not working

### ISSUE THREAD

**Issue by HanSolo72** [OpenZWave/node-red-contrib-openzwave#72]
Instances of the FGS-223 are not numbered 0 and 1 (as in the manual), but 1 and 2. It doesn't matter if I send instance 0, 1 or 2, always switch number 1 turns is switched. It's not possible to access the second switch.

Here's my command: {"nodeid":4, "instance":2}

This comes from the input if I change the status of the switch manually:
{
	"topic": "zwave: value changed",
	"payload": {
		"nodeid": 4,
		"cmdclass": 37,
		"cmdidx": 0,
		"instance": 2,
		"oldState": true,
		"currState": false,
		"label": "Instance 2: Switch",
		"units": "",
		"value": {
			"value_id": "4-37-2-0",
			"node_id": 4,
			"class_id": 37,
			"type": "bool",
			"genre": "user",
			"instance": 2,
			"index": 0,
			"label": "Instance 2: Switch",
			"units": "",
			"help": "Turn On/Off Device",
			"read_only": false,
			"write_only": false,
			"min": 0,
			"max": 0,
			"is_polled": false,
			"value": false
		},
		"uuid": "1C-69-7A-04-C3-95-0xec945d2c-4"
	},
	"_msgid": "2d574a39.382a56"
}

**Comment by ekarak** [comment]
I'm looking into this ... please see https://github.com/OpenZWave/node-openzwave-shared/issues/361

**Comment by ekarak** [comment]
fixed, version 1.2.5 released
