### ISSUE TITLE
TypeError: require(...).getMac is not a function (line:30)

### ISSUE THREAD

**Issue by PauLL54** [OpenZWave/node-red-contrib-openzwave#76]
On Raspian Buster 4.19 the following issue is seen after installation of openzwave 1.2.5:
"TypeError: require(...).getMac is not a function (line:30)"

Latest OpenZWave library version 1.6.1007 was used.
The stable release (1.6) did not compile (DoorLockLogging.cpp: warning becomes error).
How can this be fixed?

**Comment by PauLL54** [comment]
Probably, the signature of the latest version (5) of getMac has changed.

Fixed with:
Edit: /home/pi/.node-red/node_modules/node-red-contrib-openzwave/10-zwave.js
Replace line 30-33 with: 
var gm = require('getmac'); 
UUIDPREFIX = gm.default().replace(/:/gi, );

Also, the package.json file should be adapted and require version 5 for getmac.

Who can update the code?

**Comment by ekarak** [comment]
Thank you Paul, I'll provide a fix for this

**Comment by ekarak** [comment]
resolved with release 1.6.2
