### ISSUE TITLE
Getting TypeError: Illegal invocation

### ISSUE THREAD

**Issue by krvarma** [OpenZWave/node-red-contrib-openzwave#8]
I installed on Raspberry Pi 2, and created a simple flow to turn on the node 2. But when it is started getting following error:

*TypeError: Illegal invocation*

My flow is given below, could someone help me to solve this?

*[{"id":"b7dd7bbf.482288","type":"zwave-controller","port":"/dev/ttyUSB0","driverattempts":"3","pollinterval":"500"},{"id":"21ee8190.de117e","type":"debug","name":"","active":true,"console":"false","complete":"true","x":494,"y":138,"z":"5c7e5579.a381ac","wires":[]},{"id":"12af3f5b.ed50c1","type":"zwave-out","name":"","controller":"b7dd7bbf.482288","x":492,"y":445,"z":"5c7e5579.a381ac","wires":[]},{"id":"faa855fa.0557a8","type":"inject","name":"","topic":"switchOn","payload":"{nodeid: 2}","payloadType":"string","repeat":"5","crontab":"","once":false,"x":181,"y":248,"z":"5c7e5579.a381ac","wires":[["12af3f5b.ed50c1","21ee8190.de117e"]]}]*

**Comment by ekarak** [comment]
This was the message emitted when the old version of node-openzwave was
compiled against node 0.12.

The current version is using node-openzwave-shared 1.0 which should work
OK.

Which versions are you on? Afaik node-red does NOT support 0.12 btw

Thanks
Στις 23 Ιουλ 2015 10:22 μ.μ., ο χρήστης "Krishnaraj Varma" <
notifications@github.com> έγραψε:

**Comment by krvarma** [comment]
Thanks ekarak!

My node us 0.12.x, Node-RED is 0.11.1. The support for Node 0.12.x added from Node-RED 0.11.0 onward.

Let me install older node and check.

**Comment by ekarak** [comment]
For more details on the error, check https://github.com/jperkin/node-openzwave/pull/48
- My best guess is that with your current setup you're safer downgrading to node 0.10.x
- To use node 0.12 with node-red-contrib-openzwave, make sure that you're using its latest version (1.0) which pulls in *node-openzwave-shared* , a extended fork of jperkin/node-openzwave which is rewritten with the NAN headers to cater for the C++ API changes in Node 0.12.x

**Comment by vitmartino** [comment]
Hi ekarak,
I have installed node-openzwave-shared (1.0.1), Node-RED version: v0.11.1, Node.js  version: v0.12.6.
when I try to send a message to zwave receiver I get the error:
{ "topic": "setValue", "payload": { "nodeid": 178, "value": 100, "cmdclass": 37 }, "_msgid": "42f59e0a.bd0a6" }
6 Aug 13:12:22 - [error] [zwave-out:z-wave sender] TypeError: Illegal invocation

how you fix this?

**Comment by vitmartino** [comment]
I have Illegal invocation only with msg.topic switchOn, switchOff, setLevel.. using other string doesn't have any effects..

I am going to be crazy..

**Comment by ekarak** [comment]
Thanks for this vital info! You can try switching on binary loads using
setValue() as a workaround. I currently have very little spare time to
replicate this but I hope I'll deal with this in the weekend.



2015-08-06 21:08 GMT+03:00 vitmarty <notifications@github.com>:

> I have Illegal invocation only with msg.topic switchOn, switchOff,
> setLevel.. using other string doesn't have any effects..
>
> I am going to be crazy..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenZWave/node-red-contrib-openzwave/issues/8#issuecomment-128461725>
> .
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by vitmartino** [comment]
I have tried to send this message to zwave out node:
{ "topic": "setValue", "payload": { "nodeid": 178, "value": 1, "cmdclass": 37 }, "_msgid": "4d11bdda.b2ee44" }
but I still have the same error TypeError: Illegal invocation

what do you mean with "try switching on binary loads using setValue()"?

**Comment by fraser73** [comment]
I have what appears to be exactly the same problem, it appears that the issue is with node-openzwave-shared, before I saw this issue, I raised a ticket there: https://github.com/OpenZWave/node-openzwave-shared/issues/13

**Comment by pasqualeg** [comment]
hi Ekarak, I have the same error, "Illegal invocation". 
Can you give us guidance on how to solve it !? 
it would be great a working example made by you

**Comment by vitmartino** [comment]
Hi krvarma,
can you re-open this issue?

**Comment by fraser73** [comment]
All appears to be working fine after yesterday's update. If I can be of any help in the future, testing, making how to docs etc, let me know. I don't really know much javascript unfortunately, but am learning albeit slowly...

**Comment by ekarak** [comment]
thank you all for the feedback. BTW, I just published version 1.0.8 which also fixes the rampant console logging from OpenZWave.
