### ISSUE TITLE
Are advanced devices (I.e. Thermostat) supported?

### ISSUE THREAD

**Issue by bdfoster** [OpenZWave/node-red-contrib-openzwave#9]
I just had a general question of whether a thermostat such as the Honeywell Z Wave compatible thermostat is supported. I notice that it seems to be supported in node-openzwave-shared, but was unsure if the documentation was wrong/incomplete on this issue. 

Been following the node/openzwave developments and support for better integration. You sure have been busy! Your work is much appreciated.

**Comment by bdfoster** [comment]
Upon further inspection of the node-openzwave-shared docs, I may have mispoke on thermostats being supported. But I'll wait on clarification.

For the interest of full disclosure, the only thing I really need to be able to do is set the system to either 'heat', 'cool', or 'off'. I don't really need to change setpoints or anything. A bonus would be the ability to read events on whether or not the boiler or A/C has been switched on by the thermostat. I wish I had more specific information (command classes, keys, etc.), but I'm actually not on site to be able to work this out.

**Comment by ekarak** [comment]
Right, command like these *could* be supported via the generic SetValue() command. The only thing you need is examples of such commands for your device (you basically need the command class, and its arguments: index, instance and the like) - I think you're close. I'll add some wrappers for thermostat functionality in time (-if only I had the time and capital to try out new gear-, sigh)
